In [37]:
import numpy as np

#Code to generate a random 5x5 array and store the values in the variable "X"
X = np.random.rand(5, 5)

#Formula for Normalized X (Subtracting X from its mean and divide it with its standard deviation)
#.mean() is used to generate element wise mean and .std() for element-wise standard deviation
X_normalized = ((X - X.mean()) / X.std())

#Save the normalized array as X_normalized.npy
np.save('X_normalized.npy', X_normalized)

#Outputting the original and normalized value of the array
print("Original Array = \n", X)
print("\nNormalized Array = \n", X_normalized)

Original Array = 
 [[0.13659824 0.24805351 0.66086627 0.03919596 0.32467807]
 [0.53922769 0.92158615 0.23185354 0.84181312 0.87706005]
 [0.01299684 0.26333249 0.15626651 0.57736303 0.41839591]
 [0.12404907 0.63054773 0.75452456 0.95074199 0.4462766 ]
 [0.63198291 0.0906719  0.72314276 0.65573467 0.55867907]]

Normalized Array = 
 [[-1.1673233  -0.78013948  0.65392835 -1.50568849 -0.51395387]
 [ 0.23136881  1.5596416  -0.83641646  1.28251855  1.40496265]
 [-1.59670146 -0.7270619  -1.09899778  0.36384692 -0.188388  ]
 [-1.21091778  0.54860496  0.97928734  1.6609259  -0.09153346]
 [ 0.55359061 -1.32686651  0.8702703   0.6361017   0.29894083]]


In [65]:
#Line of code to initiate 100 integers and reshape to 10x10 array and square them 
A = np.arange(1, 101).reshape(10, 10) ** 2

#Determine the elements which are divisible by 3
div_by_3 = A[A % 3 == 0]

#Save the integers divisible by 3 to div_by_3.npy
np.save('div_by_3.npy', div_by_3)

#Outputting the original 10x10 array and the values divisible by 3
print("A = \n", A)
print("\nValues divisible by 3 = \n", div_by_3)

A = 
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Values divisible by 3 = 
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
